- hosts: "{{host | default ('ukmonhelper2')}}"
  vars_files: 
    - /mnt/c/Users/{{ lookup('env','USER' )}}/apikeys/mqvariables.enc
  vars:
    srcdir: "/mnt/c/Users/{{ lookup('env','USER' )}}/OneDrive/dev/ukmda-dataprocessing/archive"
  tasks:
  - name: import dev variables 
    include_vars: dev-vars.yml
    tags: dev
  - name: import prod variables
    include_vars: prod-vars.yml
    tags: prod
  - name: Ensures {{destdir}}/utils exists
    file: path={{destdir}}/utils state=directory  
    tags: [dev,prod]

  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    tags: [dev,prod]
    with_items:
    - {src: '{{srcdir}}/utils/makeConfig.sh', dest: '{{destdir}}/utils/', mode: '754', backup: yes }
    - {src: '{{srcdir}}/utils/stopstart-calcengine.sh', dest: '{{destdir}}/utils/', mode: '754', backup: yes }
    - {src: '{{srcdir}}/server_setup/.bashrc', dest: '/home/ec2-user', mode: '644', backup: yes }
    - {src: '{{srcdir}}/server_setup/.bash_aliases', dest: '/home/ec2-user', mode: '644', backup: no }
    - {src: '{{srcdir}}/server_setup/.condaon', dest: '/home/ec2-user', mode: '644', backup: no }
    
  - name: create Config file
    shell: '{{destdir}}/utils/makeConfig.sh {{env}}'
    tags: [dev,prod]
