---
- hosts: "{{host | default ('ukmonhelper2')}}"
  vars_files: 
    - /mnt/c/Users/{{ lookup('env','USER' )}}/apikeys/mqvariables.enc
  vars:
    srcdir: "/mnt/c/Users/{{ lookup('env','USER' )}}/OneDrive/dev/ukmda-dataprocessing/archive"
  tasks:
  - name: import dev variables 
    include_vars: ./dev-vars.yml
    tags: dev
  - name: import prod variables
    include_vars: ./prod-vars.yml
    tags: prod
  - name: Ensures {{destdir}}/cronjobs exists
    file: path={{destdir}}/cronjobs state=directory  
    tags: [dev,prod]
  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    tags: [dev,prod]
    with_items:
        - {src: '{{srcdir}}/cronjobs/nightlyJob.sh', dest: '{{destdir}}/cronjobs', mode: '754', backup: no }
        - {src: '{{srcdir}}/cronjobs/captureBright.sh', dest: '{{destdir}}/cronjobs', mode: '754', backup: no }
        - {src: '{{srcdir}}/cronjobs/getImoWSfile.sh', dest: '{{destdir}}/cronjobs', mode: '754', backup: no }
        - {src: '{{srcdir}}//cronjobs/mergeNewOrbit.sh', dest: '{{destdir}}/cronjobs', mode: '754', backup: no }
        - {src: '{{srcdir}}//cronjobs/gatherMonthlyVideos.sh', dest: '{{destdir}}/cronjobs', mode: '754', backup: no }
        - {src: '{{srcdir}}/cronjobs/README.md', dest: '{{destdir}}/cronjobs', mode: '644', backup: no }
