daily
rotate 7
notifempty
~/prod/logs/*.log {
    daily
    rotate 45
    compress
    delaycompress
    dateext
    notifempty
    maxage 45
    # create
}

~/dev/logs/*.log {
    daily
    rotate 45
    compress
    delaycompress
    dateext
    notifempty
    maxage 45
    # create
}
