# create a data type for RMS R90-style CSV files
import numpy
import sys

# defines the data content of the R90/R91 extract 
R90CSV = numpy.dtype([('Ver', 'U8'), ('Yr', 'i4'), ('Mth', 'i4'), ('Day', 'i4'),
    ('Hr', 'i4'), ('Min', 'i4'), ('Sec', 'f8'), ('Mag', 'f8'), ('Dur', 'f8'),
    ('Dir1', 'f8'), ('Alt1', 'f8'), ('Dir2', 'f8'), ('Alt2', 'f8'),
    ('Ra1', 'f8'), ('Dec1', 'f8'), ('Ra2', 'f8'), ('Dec2', 'f8'),
    ('Loc_Cam', 'U16'), ('Longi', 'f8'), ('Lati', 'f8'), ('Alti', 'f8'), ('TZ', 'f8')])

# fmt string for numpy.savetxt
R90CSVfmt = '%s,%d,%d,%d,%d,%d,%.2f,%.4f,%.2f,%.4f,%.4f,%.4f,%.4f,%.4f,%.4f,%.4f,%.4f,%s,%.4f,%.4f,%.4f,%d'

# extra CSV file holding orbital parameters generated by WMPL
#date, mjd,id,iau,name,mass,pi,Q,true_anom,EA,MA,Tj,T,last_peri,jacchia1,Jacchia2,numstats,stations
extraCSV = numpy.dtype([('date', 'U16'), ('mjd','f8'), ('id','U16'), ('iau', 'i4'),
    ('name','U32'), ('mass','f8'),('pi','f8'), ('Q','f8'), ('true_anom','f8'), ('EA','f8'),
    ('Ma','f8'), ('Tj','f8'), ('T','f8'), ('last_peri','f8'), ('jacchia1','f8'),
    ('jacchia2','f8'), ('numstats','i4'), ('stations','U128')])

# fmt string for numpy.savetxt
extraCSFfmt='%s,%.4f,%s,%d,%s,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%.6f,%d,%s'

# simple shower association data format
#ID,Y,M,D,h,m,s,Shwr
assocCSV = numpy.dtype([('ID','U16'), ('Yr','i4'), ('Mth','i4'), ('Day','i4'),
    ('Hr','i4'), ('Min','i4'), ('Sec','f8'), ('Shwr','U8')])

# fmt string for numpy.savetxt
assocCSVfmt='%s,%d,%d,%d,%d,%d,%.2f,%s'

# For testing.
# example: python UAdata.py 2019


def main():
    i = 0
    yr = sys.argv[1]
    fnam = 'c:/users/mark/videos/astro/meteorcam/archive/p_' + yr + '-unified.csv'
    print(fnam)
    mydata = numpy.loadtxt(fnam, delimiter=',', skiprows=1, dtype=R90CSV)

    print(mydata[i])  # print the ith row
    print(mydata['Mag'])  # print all the magnitudes
    print(mydata[i]['Mag'])  # print the mag on the ith row


if __name__ == '__main__':
    main()
