# SAM build file for searchArchive
# Copyright (C) 2018-2023 Mark McIntyre
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  searchArchive:
    Type: AWS::Serverless::Function
    Properties:
      Handler: searchArchive.lambda_handler
      Runtime: python3.11
      FunctionName: searchArchive
      Policies: AmazonS3ReadOnlyAccess
      Timeout: 60
      Description: Function to search the Archive for events matching user-supplied criteria
      Environment:
        Variables:
          SRCHBUCKET: ukmda-website
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: '/'
            Method: get
            RequestParameters: [
              'method.request.querystring.d1': {Required: true},
              'method.request.querystring.d2': {Required: true},
              'method.request.querystring.opts': {Required: false}
            ]
      Tags:
        billingtag: "ukmda"
    Metadata:
      BuildMethod: python3.11
