---
- hosts: ukmonhelper
  gather_facts: no
  tasks:
  - name: import dev variables 
    include_vars: ./dev-vars.yml
    tags: dev
  - name: import prod variables
    include_vars: ./prod-vars.yml
    tags: prod
  - name: Ensures {{windestdir}} exists
    file: path={{windestdir}} state=directory  
    delegate_to: localhost
    tags: [dev,prod]
  - name: Ensures {{windestdir}}/caminfo exists
    file: path={{windestdir}}/caminfo state=directory  
    delegate_to: localhost
    tags: [dev,prod]

  - name: build exe
    ansible.builtin.shell: | 
      conda activate ukmon-admin
      cd windows
      pyinstaller ./stationMaint2.py --noconsole --onefile --windowed --icon .\camera.ico
    args:
      executable: pwsh.exe
    delegate_to: localhost
    register: outdata
    tags: [dev,prod]

  - name: print debug
    debug:
      var: outdata.stdout
  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    delegate_to: localhost
    tags: [dev,prod]
    with_items:
    - {src: '{{winsrcdir}}/dist/StationMaint2.exe', dest: '{{windestdir}}/', mode: '754', backup: yes, directory_mode: no }
    - {src: '{{winsrcdir}}/camera.ico', dest: '{{windestdir}}/', mode: '644', backup: yes, directory_mode: no }
    - {src: '{{winsrcdir}}/stationmaint.cfg', dest: '{{windestdir}}/', mode: '644', backup: yes, directory_mode: no }
  - name: update source bucket
    lineinfile:
      path: '{{windestdir}}/stationmaint.cfg'
      regexp: 'SRCBUCKET='
      line: 'SRCBUCKET={{srcbucket}}'
    delegate_to: localhost
    tags: [dev,prod]
  - name: update live bucket
    lineinfile:
      path: '{{windestdir}}/stationmaint.cfg'
      regexp: 'LIVEBUCKET='
      line: 'LIVEBUCKET={{livebucket}}'
    delegate_to: localhost
    tags: [dev,prod]
  - name: update web bucket
    lineinfile:
      path: '{{windestdir}}/stationmaint.cfg'
      regexp: 'WEBSITEBUCKET='
      line: 'WEBSITEBUCKET={{websitebucket}}'
    delegate_to: localhost
    tags: [dev,prod]
  - name: update helper ipaddress
    lineinfile:
      path: '{{windestdir}}/stationmaint.cfg'
      regexp: 'HELPERIP='
      line: 'HELPERIP={{serverip}}'
    delegate_to: localhost
    tags: [dev,prod]
  - name: update helper remotedir
    lineinfile:
      path: '{{windestdir}}/stationmaint.cfg'
      regexp: 'REMOTEDIR='
      line: 'REMOTEDIR={{remotedir}}'
    delegate_to: localhost
    tags: [dev,prod]
