#
# Python code to analyse meteor shower data
#
# Copyright (C) 2018-2023 Mark McIntyre

import os
import boto3
import json
import pymysql.cursors


def getSqlLoginDetails():
    # retrieve password and host from SSM. This allows me to manage them from Terraform
    ssm = boto3.client('ssm', region_name='eu-west-1')
    res = ssm.get_parameter(Name='prod_dbpw', WithDecryption=True)
    password = res['Parameter']['Value']
    res = ssm.get_parameter(Name='prod_dbhost')
    host = res['Parameter']['Value'] 
    # should really do these too but they won't change often if at all
    user = 'batch'
    db = 'ukmon'
    return host, user, password, db


def getAllImages(dtstr):
    """
    Retrieve a list of all images for a given date from the SQL database
    This is a list of all images containing detections, whether or not used
    in a solution. 
    """
    host, user, passwd, db = getSqlLoginDetails()
    connection = pymysql.connect(host=host, user=user, password=passwd, database=db, cursorclass=pymysql.cursors.DictCursor)  
    sqlstr = f'select filname from singles where Y={dtstr[:4]} and M={int(dtstr[4:6])} and D={int(dtstr[6:8])}'
    with connection.cursor() as cursor:
        cursor.execute(sqlstr)
        result = cursor.fetchall()
        connection.close()
    res=[]
    for event in result:
        res.append(event['filname'])
    return res


def getKnownImages(dtstr, datatype='consumed'):
    """
    Get a list of all images that were involved in a match or were uncalibrated, 
    depending on the value of datatype (consumed or uncal)
    The raw data are generated by a process on the matching engine server
    """
    datadir=os.getenv('DATADIR', default=os.path.expanduser('~/prod/data'))
    srcfile = os.path.join(datadir,'single','used',f'{datatype}_{dtstr}.txt')
    imglist = []
    if os.path.isfile(srcfile):
        used = open(srcfile,'r').readlines()
        for img in used:
            imglist.append(img.strip())
    return imglist


def getUnusedImages(dtstr):

    allimages = getAllImages(dtstr)
    uncal = getKnownImages(dtstr, 'uncal')
    used = getKnownImages(dtstr, 'consumed')
    unused = list(set(allimages)-set(used + uncal))