#
# Python code to analyse meteor shower data
#
# Copyright (C) 2018-2023 Mark McIntyre

import os
import sys
import boto3
import json
import pymysql.cursors
import sqlite3
import re
import datetime
import numpy as np

from wmpl.Formats.CAMS import loadFTPDetectInfo
from wmpl.Utils.TrajConversions import jd2Date, datetime2JD
from wmpl.Trajectory.CorrelateRMS import MeteorObsRMS, MeteorPointRMS, PlateparDummy

def getSqlLoginDetails():
    # retrieve password and host from SSM. This allows me to manage them from Terraform
    ssm = boto3.client('ssm', region_name='eu-west-1')
    res = ssm.get_parameter(Name='prod_dbpw', WithDecryption=True)
    password = res['Parameter']['Value']
    res = ssm.get_parameter(Name='prod_dbhost')
    host = res['Parameter']['Value'] 
    # should really do these too but they won't change often if at all
    user = 'batch'
    db = 'ukmon'
    return host, user, password, db


def getAllImages(dtstr):
    """
    Retrieve a list of all images for a given date from the SQL database
    This is a list of all images containing detections, whether or not used
    in a solution. 
    """
    host, user, passwd, db = getSqlLoginDetails()
    connection = pymysql.connect(host=host, user=user, password=passwd, database=db, cursorclass=pymysql.cursors.DictCursor)  
    sqlstr = f'select filname from singles where Y={dtstr[:4]} and M={int(dtstr[4:6])} and D={int(dtstr[6:8])}'
    with connection.cursor() as cursor:
        cursor.execute(sqlstr)
        result = cursor.fetchall()
        connection.close()
    res=[]
    for event in result:
        res.append(event['filname'])
    return res


def getKnownImages(dtstr, datatype='consumed'):
    """
    Get a list of all images that were involved in a match or were uncalibrated, 
    depending on the value of datatype (consumed or uncal)
    The raw data are generated by a process on the matching engine server
    """
    datadir=os.getenv('DATADIR', default=os.path.expanduser('~/prod/data'))
    srcfile = os.path.join(datadir,'single','used',f'{datatype}_{dtstr}.txt')
    imglist = []
    if os.path.isfile(srcfile):
        used = open(srcfile,'r').readlines()
        for img in used:
            imglist.append(img.strip())
    return imglist


def getUncalibratedImageList(dtstr=None):
    datadir=os.getenv('DATADIR', default=os.path.expanduser('~/prod/data'))
    now = datetime.datetime.now(tz=datetime.timezone.utc).strftime('%Y%m%d')

    host, user, passwd, db = getSqlLoginDetails()
    connection = pymysql.connect(host=host, user=user, password=passwd, database=db, cursorclass=pymysql.cursors.DictCursor)  
    cur = connection.cursor()

    if dtstr is not None and dtstr != now:
        logfile = os.path.join(datadir, '..', 'logs', f'matchJob.log-{dtstr}')
    else:
        logfile = os.path.join(datadir, '..', 'logs', 'matchJob.log')
    if os.path.isfile(logfile):
        flines = open(logfile, 'r').readlines()
        uncal = [f for f in flines if 'not recalibrated' in f]
        imglist = [x.split('Skipping ')[1].split(',')[0] for x in uncal]
        with open(os.path.join(datadir, 'single', 'used', f'uncal_{dtstr}.txt'), 'w') as outf:
            for li in imglist:
                outf.write(f'{li}\n')
                sqlstr = f"update singles set status='U' where filname='{li}"
                cur.execute(sqlstr)
    else:
        print('file not found', logfile)
        imglist=[]
    cur.commit()
    cur.close()
    connection.close()
    return imglist


def getUnusedImages(dtstr):
    """
    Find all images for 'dtstr' which are not associated with a
    match in the matches database
    """

    allimages = getAllImages(dtstr)
    uncal = getKnownImages(dtstr, 'uncal')
    used = getKnownImages(dtstr, 'consumed')
    unused = list(set(allimages)-set(used + uncal))
    datadir=os.getenv('DATADIR', default=os.path.expanduser('~/prod/data'))
    with open(os.path.join(datadir,'single','used',f'unused_{dtstr}.txt'), 'w') as outf:
        pass

    #   df.index[df.a==3].tolist() to get row indexes where column a == 3
    #   df.loc[1, 'b'] = 5 to set row 1, column 'b' to value 5


##########################################################
# Handling of observations
# This has to be run on the calcserver as it needs access
# to the raw RMS data.
##########################################################

def initMeteorObs(station_code, ftpdetectinfo_path, platepars_recalibrated_dict):
    """ Init meteor observations from the FTPdetectinfo file and recalibrated platepars. """
    # Load station coordinates
    if len(list(platepars_recalibrated_dict.keys())):
        pp_dict = platepars_recalibrated_dict[list(platepars_recalibrated_dict.keys())[0]]
        pp = PlateparDummy(**pp_dict)
        stations_dict = {station_code: [np.radians(pp.lat), np.radians(pp.lon), pp.elev]}
        # Load the FTPdetectinfo file
        meteor_list = loadFTPDetectInfo(ftpdetectinfo_path, stations_dict, join_broken_meteors=False)
    else:
        meteor_list = []
    return meteor_list


def openAllObsDb(dbdir, dbname='all_observations.db', force_create=False):
    allobsdb = os.path.join(dbdir, dbname)
    if not os.path.isfile(allobsdb) and not force_create:
        return None        
    # otherwise, open the database, which will create it if necessary 
    con = sqlite3.connect(allobsdb)
    con.execute('pragma journal_mode=wal')
    # check and add the tables if missing
    res = con.execute("SELECT name FROM sqlite_master WHERE name='all_obs'")
    if res.fetchone() is None:
        con.execute("CREATE TABLE all_obs(obs_id VARCHAR(36) UNIQUE, obs_dt REAL, paired INTEGER, status INTEGER)")
    con.commit()
    return con  


def getAllObservations(dt_range, dbdir, datadir):
    """
    Find all observations in 'datadir' within 'dt_range' and add them to the all-observations database in dbdir. 

    Arguments
    dt_range:   [tuple] pair of datetimes representing the range to be scanned
    dbdir:      [string] the location of the all-obs database
    datadir:    [string] the location of the RMS data to be scanned
    """


    dbname = 'all_observations.db'
    con = openAllObsDb(dbdir, dbname, force_create=True)

    avail_station_list = []

    # get a list of stations of interest
    for dir_name in sorted(os.listdir(datadir)):
        # Check if the dir name matches the station name pattern
        if os.path.isdir(os.path.join(datadir, dir_name)):
            if re.match("^[A-Z]{2}[A-Z0-9]{4}$", dir_name):
                print("Using station: " + dir_name)
                avail_station_list.append(dir_name)
            else:
                print("Skipping directory: " + dir_name)

    processing_list = []

    # Go through all station directories
    for station_name in avail_station_list:
        station_path = os.path.join(datadir, station_name)
        # Go through all directories in stations
        for night_name in os.listdir(station_path):
            # Extract the date and time of directory, if possible
            try:
                night_dt = datetime.datetime.strptime("_".join(night_name.split("_")[1:3]), 
                    "%Y%m%d_%H%M%S").replace(tzinfo=datetime.timezone.utc)
            except:
                print(f'Could not parse the date of the night dir: {night_name}')
                night_dt = None
                continue
            if dt_range is not None:
                # skip folders more than a day older the requested date range
                if night_dt < (dt_range[0]+ datetime.timedelta(days=-1)).replace(tzinfo=datetime.timezone.utc):
                    continue
            night_path = os.path.join(station_path, night_name)
            night_path_rel = os.path.join(station_name, night_name)
            processing_list.append([station_name, night_path_rel, night_path, night_dt])

    ### Now process the folders
    unpaired_met_obs_list = []
    prev_station = None
    station_count = 1

    total_obs_added = 0
    for station_code, rel_proc_path, proc_path, night_dt in processing_list:
        # Check that the night datetime is within the given range of times, if the range is given
        if (dt_range is not None) and (night_dt is not None):
            dt_beg, dt_end = dt_range

            # Skip all folders which are outside the limits 
            # allow a day before dt_beg to capture data overlapping from an earlier timezone
            if (night_dt < dt_beg + datetime.timedelta(days=-1)) or (night_dt > dt_end):
                print(f'skipping {rel_proc_path}')
                continue

        #print("")
        #print(f"Processing station: {station_code} {rel_proc_path}")

        ftpdetectinfo_name = None
        platepar_recalibrated_name = None

        # Skip files, only take directories
        if os.path.isfile(proc_path):
            continue

        # Find FTPdetectinfo and platepar files and skip if they're not both present
        file_list = os.listdir(proc_path)
        joined_file_list = ' '.join(file_list)

        if 'FTPdetectinfo' not in joined_file_list or 'platepars_all_recalibrated.json' not in joined_file_list:
            continue

        # okay, we at least have the required files, lets try loading them
        for name in file_list:
                
            # Find FTPdetectinfo
            if name.startswith("FTPdetectinfo") and name.endswith('.txt') and \
                    ("backup" not in name) and ("uncalibrated" not in name) and ("unfiltered" not in name):
                ftpdetectinfo_name = name
                continue

            if name == "platepars_all_recalibrated.json":

                try:
                    # Try loading the recalibrated platepars
                    with open(os.path.join(proc_path, name)) as f:
                        platepars_recalibrated_dict = json.load(f)                            
                        platepar_recalibrated_name = name
                        continue

                except:
                    pass

        
        # Skip these observations if no data files were found inside
        if (ftpdetectinfo_name is None) or (platepar_recalibrated_name is None):
            #print(f"  Skipping {rel_proc_path} due to missing data files...")
            continue

        if len(platepars_recalibrated_dict) == 0:
            #print(f"  Skipping {rel_proc_path} due to no observations...")
            continue

        # More accurate check that the night datetime is within the given range of times, if the range is given
        if (dt_range is not None) and (night_dt is not None):
            dt_beg, dt_end = dt_range

            # Find the time of the latest detection in this dataset. 
            # We add on 10s to the time of the latest detection to allow for the duration of an RMS FF block

            latest_obs = datetime.datetime.strptime(list(platepars_recalibrated_dict.keys())[-1][10:25], '%Y%m%d_%H%M%S')
            latest_obs = latest_obs.replace(tzinfo=datetime.timezone.utc) + datetime.timedelta(seconds=10)

            # Filter out any folders whose start-date is after the bucket end date, or whose
            # latest observaton is before the bucket start date.

            if (latest_obs < dt_beg) or (night_dt > dt_end):
                # log.info(f'skipping {rel_proc_path} as no relevant observations')
                continue

        if station_code != prev_station:
            station_count += 1
            prev_station = station_code

        # Load platepars
        with open(os.path.join(proc_path, platepar_recalibrated_name)) as f:
            platepars_recalibrated_dict = json.load(f)

        # If all files exist, init the meteor container object
        cams_met_obs_list = initMeteorObs(station_code, os.path.join(proc_path, ftpdetectinfo_name), platepars_recalibrated_dict)

        # Format the observation object to the one required by the trajectory correlator
        added_count = 0
        for cams_met_obs in cams_met_obs_list:

            obs_dt = jd2Date(cams_met_obs.jdt_ref, dt_obj=True, tzinfo=datetime.timezone.utc)

            if dt_range and (obs_dt < dt_beg or obs_dt > dt_end):
                #log.info(f'skipping {cams_met_obs.ff_name} as outside current bucket')
                continue

            # Get the platepar
            if cams_met_obs.ff_name in platepars_recalibrated_dict:
                pp_dict = platepars_recalibrated_dict[cams_met_obs.ff_name]
            else:
                #print("    Skipping {:s}, not found in platepar dict".format(cams_met_obs.ff_name))
                continue

            pp = PlateparDummy(**pp_dict)

            # Skip observations which weren't recalibrated
            if hasattr(pp, "auto_recalibrated"):
                if not pp.auto_recalibrated:
                    #print("    Skipping {:s}, not recalibrated!".format(cams_met_obs.ff_name))
                    continue

            # Init meteor data
            meteor_data = []
            for entry in zip(cams_met_obs.frames, cams_met_obs.time_data, cams_met_obs.x_data,
                    cams_met_obs.y_data, cams_met_obs.azim_data, cams_met_obs.elev_data, 
                    cams_met_obs.ra_data, cams_met_obs.dec_data, cams_met_obs.mag_data):

                frame, time_rel, x, y, azim, alt, ra, dec, mag = entry

                met_point = MeteorPointRMS(frame, time_rel, x, y, np.degrees(ra), np.degrees(dec), 
                    np.degrees(azim), np.degrees(alt), mag)

                meteor_data.append(met_point)

            # Init the new meteor observation object
            met_obs = MeteorObsRMS(station_code, obs_dt, pp,meteor_data, rel_proc_path, ff_name=cams_met_obs.ff_name)

            # Skip bad observations
            if met_obs.bad_data:
                continue
            jdt_ref = datetime2JD(met_obs.reference_dt)
            con.execute(f"insert into all_obs values ('{met_obs.obs_id}', {jdt_ref}, 0, 1) on conflict(obs_id) do nothing")
            con.commit()
            added_count += 1
            
        print(f'  Added {added_count} observations from {rel_proc_path}')
        total_obs_added += added_count

    print(f'Finished adding {total_obs_added} observations')
    con.close()
    markObsPaired(dbdir)
    return


def markObsPaired(dbdir, allobsdb=None, obsdb=None, obsdbdir=None):
    """
    Mark observatious as paired in the all-observations database

    arguments:
    dbdir:      the location of the all-observations database
    
    keyword arguments:
    allobsdb:   the name of the all-observations database, default 'all_observations.db'
    obsdb:      the name of the paired observations database, default 'observations.db'
    obsdbdir:   the location of the paired-obs database, default same as all-obs

    """
    if not allobsdb:
        allobsdb = 'all_observations.db'
    if not obsdb:
        obsdb = 'observations.db'
    if not obsdbdir:
        obsdbdir = dbdir
    con = openAllObsDb(dbdir, dbname=allobsdb, force_create=False)
    if con:
        source_db_path = os.path.join(obsdbdir, obsdb)
        if os.path.isfile(source_db_path):
            cur = con.execute('select count(*) from all_obs where paired=1')
            vals = cur.fetchall()
            paired_before = vals[0][0]
            con.execute(f"attach database '{source_db_path}' as sourcedb")
            con.execute('update all_obs set paired=1 where obs_id in (select obs_id from sourcedb.paired_obs where status=1)')
            con.commit()
            con.execute("detach database 'sourcedb'")
            cur = con.execute('select count(*) from all_obs where paired=1')
            vals = cur.fetchall()
            paired_after = vals[0][0]
            con.close()
            print(f'marked {paired_after - paired_before} observations paired')
        else:
            print(f'unable to open observations.db in {obsdbdir}')
    else:
        print(f'unable to open all_observations.db in {dbdir}')



if __name__ == '__main__':
    if len(sys.argv) < 2:
        print('usage: getUsedUnused.py action {args}')
    else:
        action = sys.argv[1]
        if action.lower() == 'updateobs':
            start = int(sys.argv[2])
            end = int(sys.argv[3])
            dbdir = os.path.expanduser(sys.argv[4])
            datadir = os.path.expanduser(sys.argv[5])

            dt_beg = datetime.datetime.now(tz=datetime.timezone.utc) - datetime.timedelta(days=start)
            dt_end = datetime.datetime.now(tz=datetime.timezone.utc) - datetime.timedelta(days=end)
            dt_range = [dt_beg, dt_end]
            getAllObservations(dt_range, dbdir, datadir)
        elif action.lower() == 'unusedimgs':
            dtstr = sys.argv[2]
            getUnusedImages(dtstr)