# SAM build file for searchArchive
# Copyright (C) 2018-2023 Mark McIntyre
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  fetchECSV:
    Type: AWS::Serverless::Function
    Properties:
      Handler: fetchECSV.lambda_handler
      Runtime: python3.11
      FunctionName: fetchECSV
      Description: API backend that retrieves an ECSV file for a detection
      Timeout: 30
      Policies: [AmazonS3ReadOnlyAccess, AmazonDynamoDBReadOnlyAccess]
      Environment:
        Variables:
          ARCHBUCKET: ukmda-shared
          MPLCONFIGDIR: /tmp/mpl
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: '/'
            Method: get
            RequestParameters: 
              - method.request.querystring.stat:
                  Required: true
              - method.request.querystring.dt: 
                  Required: true
              - method.request.querystring.metcount: 
                  Required: false
      Tags:
        billingtag: "ukmda"
        typetag: "api"
    Metadata:
      BuildMethod: python3.11
