#!/bin/bash
#
# consolidate the raw RMS and UFO data. 
#
# Parameters:
#   year to process
#
# Consumes:
#   single-station data preprocessed by getRMSSingleData.sh (which includes converted UFO data)
#   csv and extracsv files created by the matching engine 
#
# Produces:
#   Updated consolidated ukmon single-event CSV file in standard UFO R91 format
#   Updated matched data files (matches-{yr} and matches-extras-{yr})
#   
# The outputs are used for downstream processing and reporting

here="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
source $here/../config/config.ini >/dev/null 2>&1

source $HOME/venvs/${WMPL_ENV}/bin/activate
export PYTHONPATH=$RMS_LOC:$wmpl_loc:$PYLIB

yr=$1
if [ "$yr" == "" ] ; then
    yr=$(date +%Y)
fi 

cd ${DATADIR}
logger -s -t consolidateOutput "Backing up previous days data"

# this creates an R91 compatible file with four extra columns which UFO Orbit ignores
export DATADIR
python $PYLIB/converters/UKMONtoUFOR91.py ${yr} $DATADIR/UKMON-all-single.csv
 
# get the latest matched data generated by WMPL
logger -s -t consolidateOutput "getting matched detections for $yr"
if [ ! -f ${DATADIR}/matched/matches-$yr.csv ] ; then 
    cp $here/templates/UO_header.txt ${DATADIR}/matched/matches-$yr.csv
    mkdir ${DATADIR}/orbits/${yr}/csv/processed > /dev/null 2>&1
fi
cat ${DATADIR}/orbits/$yr/csv/$yr*.csv >> ${DATADIR}/matched/matches-$yr.csv
mv ${DATADIR}/orbits/$yr/csv/$yr*.csv ${DATADIR}/orbits/${yr}/csv/processed

logger -s -t consolidateOutput "getting extra orbit data for $yr"
if [ ! -f ${DATADIR}/matched/matches-extras-$yr.csv ] ; then 
    cp $here/templates/extracsv.txt ${DATADIR}/matched/matches-extras-$yr.csv
    mkdir ${DATADIR}/orbits/${yr}/extracsv/processed > /dev/null 2>&1
fi
cat ${DATADIR}/orbits/$yr/extracsv/$yr*.csv >> ${DATADIR}/matched/matches-extras-$yr.csv
mv ${DATADIR}/orbits/$yr/extracsv/$yr*.csv ${DATADIR}/orbits/${yr}/extracsv/processed

logger -s -t consolidateOutput "consolidation done"

