# SAM build file for searchArchive
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  searchArchive:
    Type: AWS::Serverless::Function
    Properties:
      Handler: searchArchive.lambda_handler
      Runtime: python3.8
      FunctionName: searchArchive
      Policies: AmazonS3ReadOnlyAccess
      Timeout: 60
      Environment:
        Variables:
          SRCHBUCKET: ukmeteornetworkarchive
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: '/'
            Method: get
      Tags:
        billingtag: "ukmon"
    Metadata:
      BuildMethod: python3.8
