AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  freecycle

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  monitorLive:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Description: Triggered when a jpg is uploaded to the live bucket
      FunctionName: monitorLive
      CodeUri: pythoncode/
      Handler: monitorLiveFeed.lambda_handler
      Runtime: python3.14
      Timeout: 900
      MemorySize: 512
      EphemeralStorage:
        Size: 512
      Architectures:
        - x86_64
      Tags:
        billingtag: "ukmda"
      Role: arn:aws:iam::183798037734:role/service-role/monitorLiveRole
      Environment:
        Variables:
          TMP: "/tmp"
