daily
rotate 7
notifempty
/home/ec2-user/prod/logs/*.log {
    daily
    rotate 45
    compress
    delaycompress
    dateext
    notifempty
    maxage 45
    # create
}

/home/ec2-user/dev/logs/*.log {
    daily
    rotate 45
    compress
    delaycompress
    dateext
    notifempty
    maxage 45
    # create
}
